version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  api:
    container_name: fastrack_api
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8100:8000"
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5800:5432"
