version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  api:
    container_name: fastrack_api
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DOMAIN: 'http://localhost:8100'
      DATABASE_URL: 'postgresql://fastrackuser:fastrackpass@db:5432/fastrack'
    ports:
      - "8100:8000"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'fastrackpass'
      POSTGRES_USER: 'fastrackuser'
      POSTGRES_DB: 'fastrack'
    ports:
      - "5800:5432"
