# Generated by Django 3.0.8 on 2020-07-13 05:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_uuid', models.UUIDField()),
                ('session_uuid', models.UUIDField()),
                ('domain', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=20)),
                ('referrer', models.CharField(max_length=120)),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('history_uuid', models.UUIDField()),
            ],
        ),
    ]
