# Generated by Django 3.0.8 on 2020-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_auto_20200713_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewmodel',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
