# Generated by Django 3.0.8 on 2020-07-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_pageviewmodel_time_spent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodel',
            unique_together={('email', 'history_uuid')},
        ),
    ]
