# Generated by Django 3.0.8 on 2020-08-06 03:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_auto_20200715_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviewmodel',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
